### ISSUE TITLE
why always pending when i test in website

### ISSUE THREAD

**Issue by linqinghong** [mcordts/cityscapesScripts#77]
Does anyone have a situation like me? After i submit, I have been waiting "pending", whether the result of my submission is wrong or the problem of the website. Thank!

**Comment by chengyangfu** [comment]
I also have the same situation. If the format is correct, does anyone know how long the evaluation takes? If the format is wrong, does the evaluation server send out some error messages?

**Comment by linqinghong** [comment]
> I also have the same situation. If the format is correct, does anyone know how long the evaluation takes? If the format is wrong, does the evaluation server send out some error messages?
> BTW, I saw it needs to wait around 48 hours now for the pixel-level semantic labeling. Is this normal? L

Hi, i think you should try to check the format if right again, last time i find it is my unicode format wrong, we should submit “unit-8” but i submit "unit-16" and the evaluation server didn't give any information about it,  after i update, i give the result a few minute.
48 hours is normal, if you want to submit quickly, you can try to register a new email to submit result.
hoping to help you :)

**Comment by mcordts** [comment]
Unfortunately, the server does not send notifications if the evaluation failed. If an evaluation status is "pending" for longer than 12 hours, it's best to reach out to us via email.
The 48 hour limit is on purpose in order to achieve fairness between results and to prevent overfitting by too many test set evaluations. If you try to circumvent this by using multiple email addresses you and possibly your email domain will be blocked from registering, accessing the data, and submitting.

**Comment by chengyangfu** [comment]
Hi, 
    Thanks for the reply! I found out I save the image in 'int-16" format and it causes the problem for evaluation. After fixing it, the evaluation goes well.
